FROM ghcr.io/dbt-labs/dbt-snowflake:1.3.latest

# Install AZ CLI
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

#copy DBT project
COPY dbt_docs /dbt

WORKDIR /dbt

# Run dbt
ENTRYPOINT ["dbt", "docs", "serve", "--port", "8080"]
