dbt_project_dwh:
  target: test
  outputs:
    test:
      type: snowflake
      account: xxx.west-europe.azure

      # User/password auth
      user: xxx
      password: xxx

      role: TEST_DWH_OPS
      warehouse: TEST
      database: REFINED
      schema: TEST_DWH

      threads: 8
      client_session_keep_alive: False
      # query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
